// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using EF_Core_Loading_Types.Entities.NorthWind;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace EF_Core_Loading_Types.Contexts
{
    public partial interface INorthwindContextProcedures
    {
        Task<List<SalesbyYearResult>> SalesbyYearAsync(DateTime? Beginning_Date, DateTime? Ending_Date, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
